replicaCount: 1
image:
  repository: busybox
  pullPolicy: IfNotPresent
  tag: "1.37"
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""
podAnnotations: {}
podLabels: {}
podSecurityContext:
  fsGroup: 101
  fsGroupChangePolicy: Always
securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 101
  runAsGroup: 101
  allowPrivilegeEscalation: false
service:
  type: ClusterIP
  port: 8080
  annotations: {}
ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: sample-app-tls
      hosts:
        - chart-example.local
  tlsSecret:
    create: true
    name: "sample-app-tls"
    cert: "BEGIN CERTIFICATE-----\n...\n-----END CERTIFICATE-----"
    key: "BEGIN PRIVATE KEY-----\n...\n-----END PRIVATE KEY-----"
resources: {}
livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http
command:
- /bin/sh
- -c
args:
- |
  mkdir -p /tmp/www; echo OK > /tmp/www/index.html; exec busybox httpd -f -p 0.0.0.0:8080 -h /tmp/www
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
volumes:
- name: tmp
  emptyDir: {}
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false
volumeMounts:
- name: tmp
  mountPath: /tmp
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true
nodeSelector: {}
tolerations: []
affinity: {}
envSecret:
  enabled: true
  data: 
    SAMPLE_ENV_VAR: "sample-value"
config:
  enabled: true
  mountPath: /config
  files: 
    sample-app.conf: |
      # Sample configuration file
      key: value
persistence:
  enabled: true
  existingClaim: ""
  accessMode: ReadWriteMany
  size: 5Gi
  storageClassName: "efs-sc" 
  mountPath: /data
topologySpreadConstraints:
  enabled: true
  maxSkew: 1
  whenUnsatisfiable: ScheduleAnyway
storageClass:
  enabled: true
  name: "efs-sc"
  parameters:
    fileSystemId: ""
    provisioningMode: "efs-ap"
    directoryPerms: "750"
    gidRangeStart: "1000"
    gidRangeEnd: "2000"
    basePath: "/dynamic_provisioning"
  mountOptions:
    - tls
  reclaimPolicy: Delete
  volumeBindingMode: WaitForFirstConsumer
  allowVolumeExpansion: true
