{{- if .Values.config.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sample-app.fullname" . }}-config
  labels:
    {{- include "sample-app.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.config.files }}
  {{ $key }}: |-
    {{- $val | nindent 4 }}
  {{- end }}
{{- end }}
