{{- if .Values.envSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sample-app.fullname" . }}-env
  labels:
    {{- include "sample-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.envSecret.data }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
