{{- $cfg := .Values.ingress.tlsSecret -}}
{{- if and $cfg $cfg.create -}}
{{- $name := $cfg.name | default ( ((index .Values.ingress.tls 0).secretName) | default (printf "%s-tls" (include "sample-app.fullname" .)) ) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  labels:
    {{- include "sample-app.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  {{- /* Allow both data (base64) and stringData (raw) via values; here we base64-encode if raw provided */ -}}
  {{- if $cfg.cert }}
  tls.crt: {{ $cfg.cert | b64enc }}
  {{- end }}
  {{- if $cfg.key }}
  tls.key: {{ $cfg.key | b64enc }}
  {{- end }}
{{- end }}
