name: Terraform Pipeline

on:
  workflow_dispatch:
    inputs:
      accountId:
        description: "AWS Account ID to assume role into"
        required: false
        type: string
        default: "879381243152"
      environmentName:
        description: "Environment name to deploy to"
        required: false
        type: string
        default: "test"
      destroyTerraform:
        description: "Only do terraform destroy"
        type: boolean
        default: false
        required: false
  push:
    branches: [ "main" ]
  pull_request:
    branches:
      - "**"

permissions:
  id-token: write
  contents: read

jobs:

  deploy-tf:
    uses: ./.github/workflows/deploy-tf.yaml
    with:
      accountId: ${{ inputs.accountId || '879381243152' }}
      environmentName: ${{ inputs.environmentName || 'test' }}
      projectName: "maybank-cloud-dev"
      version: ${{ github.sha }}
      destroyTerraform: ${{ inputs.destroyTerraform || false }}
    secrets: inherit

  deploy-edge-tf:
    uses: ./.github/workflows/deploy-tf.yaml
    with:
      accountId: ${{ inputs.accountId || '879381243152' }}
      environmentName: ${{ inputs.environmentName || 'test' }}
      projectName: "maybank-cloud-dev-edge"
      region: "us-east-1"
      deployDirectory: "deploy/modules/edge"
      version: ${{ github.sha }}
      destroyTerraform: ${{ inputs.destroyTerraform || false }}
      build-args: |
        CORE_STATE_PROJECT_NAME=maybank-cloud-dev
        ORIGIN_REGION=ap-southeast-1
    secrets: inherit
    needs: [deploy-tf]

  deploy-eks-tf:
    uses: ./.github/workflows/deploy-tf.yaml
    with:
      accountId: ${{ inputs.accountId || '879381243152' }}
      environmentName: ${{ inputs.environmentName || 'test' }}
      projectName: "maybank-cloud-dev-eks"
      deployDirectory: "deploy/modules/eks"
      version: ${{ github.sha }}
      destroyTerraform: true
      build-args: |
        CORE_STATE_PROJECT_NAME=maybank-cloud-dev
        ORIGIN_REGION=ap-southeast-1
    secrets: inherit
    needs: [deploy-tf]

  deploy-app-tf:
    uses: ./.github/workflows/deploy-tf.yaml
    with:
      accountId: ${{ inputs.accountId || '879381243152' }}
      environmentName: ${{ inputs.environmentName || 'test' }}
      projectName: "maybank-cloud-dev-app"
      deployDirectory: "deploy/modules/app"
      version: ${{ github.sha }}
      destroyTerraform: true
      build-args: |
        CLUSTER_STATE_BUCKET="terraform-rafiqi-personal"
        CLUSTER_STATE_REGION="ap-southeast-1"
        CLUSTER_STATE_PROJECT_NAME=maybank-cloud-dev-eks
        CORE_STATE_PROJECT_NAME=maybank-cloud-dev
    secrets: inherit
    needs: [deploy-eks-tf]
